#!/bin/bash
# get Teleblocher podcast and store it on DLNA

addr="http://www.teleblocher.ch/feed"
content=$(wget $addr -q -O -)
mp4=$(echo "$content" | grep -m1 "enclosure url=" | head -1)
file=$(echo "$mp4" | awk -F"\"" '{print $2}')
check=${file##*/}
if [ ! -f "/media/DLNA/Teleblocher/$check" ]; then
  wget -q $file
  file=${file##*/}
  new=${file##*/}
  new=${new%'?'*}
  cp $new /media/DLNA/Teleblocher && rm $new
fi
